### ISSUE TITLE
Is Possible?

### ISSUE THREAD

**Issue by VisionR1** [israpps/BDMAssault#4]
Hi, thanks for this, is possible this can't work with some? Because i try 2-3 and can't get it work with ExFat

**Comment by israpps** [comment]
The answer will be as vague as the question:

Not sure what you mean.


***
So please Be more specific, you're not even mentioning Wich homebrew app you're trying to use with this

**Comment by VisionR1** [comment]
> The answer will be as vague as the question:
> 
> Not sure what you mean.
> 
> So please Be more specific, you're not even mentioning Wich homebrew app you're trying to use with this

Sorry, i try the sms and argon, can't get it it work with ExFat

**Comment by israpps** [comment]
#2 was converted into a discussion (#3)

You should check if both SMS and argon are capable of loading external USB drivers

**Comment by VisionR1** [comment]
> #2 was converted into a discussion (#3)
> 
> You should check if both SMS and argon are capable of loading external USB drivers

Work normal with Fat32 without problem, i try so many times to make it wotk with ExFat but still not working and i don't know why and can't get a answer or anyone test it if work

**Comment by israpps** [comment]
Argod does not seem to load external USB drivers. so it cannot be used with BDMAssault

**Comment by VisionR1** [comment]
> Argod does not seem to load external USB drivers. so it cannot be used with BDMAssault

Oh understand, i have the SMS for listen music from PS2, the argon only just test

**Comment by VisionR1** [comment]
@israpps The strange is i make the change you write in readme for sms but still blank, maybe i do some noob i can't understand
with all CAPS the sms can't see the usb, and with small letter the sms see the usb (i see the icon) but not showing anything inside

**Comment by israpps** [comment]
> @israpps The strange is i make the change you write in readme for sms but still blank, maybe i do some noob i can't understand, with all CAPS the sms can't see the usb (Available media:none), and i try it with small letter the sms see the usb (i see the icon) but not showing anything inside

Not sure then, maybe SMS simply does not support this🤷🏻‍♂️

**Comment by VisionR1** [comment]
> > @israpps The strange is i make the change you write in readme for sms but still blank, maybe i do some noob i can't understand, with all CAPS the sms can't see the usb (Available media:none), and i try it with small letter the sms see the usb (i see the icon) but not showing anything inside
> 
> Not sure then, maybe SMS simply does not support this🤷🏻‍♂️

Yeah, too bad my favorite to listen music, I have see, you have in your repositories a SMS and you say with EXFAT support, but i don't see elf file

**Comment by VisionR1** [comment]
> > > > @israpps The strange is i make the change you write in readme for sms but still blank, maybe i do some noob i can't understand, with all CAPS the sms can't see the usb (Available media:none), and i try it with small letter the sms see the usb (i see the icon) but not showing anything inside
> > > 
> > > 
> > > Not sure then, maybe SMS simply does not support this🤷🏻‍♂️
> > 
> > 
> > Yeah, too bad my favorite to listen music, I have see, you have in your repositories a SMS and you say with EXFAT support, but i don't see elf file
> 
> It is a fork I was working in.
> 
> Abandoned it due to how annoying is to deal with the shitty code style of SMS

Oh understand, as i can see your good programμer, you can make your homebrew app, some similar like SMS with music all format support

**Comment by VisionR1** [comment]
I see the SMS when click start USB support, down say: Locating USBD.IRX, Probably only read from inside the elf and can't trick with this, with your knowledge can you add only your mod USBD.IRX into the SMS ? Because you say have shitty code style, but only if replace only this one, if it's possible

![IMG_20240116_180439](https://github.com/israpps/BDMAssault/assets/25982450/2ca2ed9d-f9f7-42a4-a6d8-e9d0df09fb2c)

**Comment by israpps** [comment]
just to let you know

SMS cannot benefit from BDMAssault because it uses a non standar USB driver to access the usb contents.

While all homebrews map the usb as `mass:/` the ~~fool~~ developer that made SMS decided it was a good idea to ignore what everyone else was doing and make a custom usb driver that maps the usb as `ums:/`. resulting in BDMAssault not working with SMS

**Comment by VisionR1** [comment]
> just to let you know
> 
> SMS cannot benefit from BDMAssault because it uses a non standar USB driver to access the usb contents.
> 
> While all homebrews map the usb as `mass:/` the ~fool~ developer that made SMS decided it was a good idea to ignore what everyone else was doing and make a custom usb driver that maps the usb as `ums:/`. resulting in BDMAssault not working with SMS

Thank you for the info.
Oh this is bad.
I have try in past to change this, but I'm not so good lol.

**Comment by israpps** [comment]
> > just to let you know
> > SMS cannot benefit from BDMAssault because it uses a non standar USB driver to access the usb contents.
> > While all homebrews map the usb as `mass:/` the ~fool~ developer that made SMS decided it was a good idea to ignore what everyone else was doing and make a custom usb driver that maps the usb as `ums:/`. resulting in BDMAssault not working with SMS
> 
> Thank you for the info. Oh this is bad. I have try in past to change this, but I'm not so good lol. I watch in PSX about SMS with exFAT.

yes, i'm touching sms SRC to make EXFAT and MX4SIO possible. but this crap is very hard to deal and debug

**Comment by VisionR1** [comment]
> > > just to let you know
> > > SMS cannot benefit from BDMAssault because it uses a non standar USB driver to access the usb contents.
> > > While all homebrews map the usb as `mass:/` the ~fool~ developer that made SMS decided it was a good idea to ignore what everyone else was doing and make a custom usb driver that maps the usb as `ums:/`. resulting in BDMAssault not working with SMS
> > 
> > 
> > Thank you for the info. Oh this is bad. I have try in past to change this, but I'm not so good lol. I watch in PSX about SMS with exFAT.
> 
> yes, i'm touching sms SRC to make EXFAT and MX4SIO possible. but this crap is very hard to deal and debug

Understand.
Thanks you for your hard work.
If anyone can do this, is you.
