### ISSUE TITLE
FreeMcBoot Configurator not able to read mass storage device

### ISSUE THREAD

**Issue by RoboMWM** [israpps/BDMAssault#6]
I installed this to FreeMcBoot, via using LaunchELF to copy the SYS-CONF directory (from READY_TO_USE/FreeMcBoot) to the memory card's SYS-CONF.

FreeMcBoot no longer freezes with an exFAT-formatted USB drive.

~~However, not only is OPL v1.2 is still unable to see my games, but on my other USB drive (that still has fat32) that has OPL v1.0 - OPL v1.0 does not launch and is stuck at a black screen instead.~~

~~Additionally,~~ FreeMcBoot Configurator shows a fat32-formatted USB flash drive as blank.

**Comment by israpps** [comment]
> I installed this to FreeMcBoot, via using LaunchELF to copy the SYS-CONF directory (from READY_TO_USE/FreeMcBoot) to the memory card's SYS-CONF.
> 
> FreeMcBoot no longer freezes with an ExFat-formatted USB drive.

as expected

> However, not only is OPL v1.2 is still unable to see my games,
not BDMAssault fault/responsibility. OPL uses it's own usb driver


> but on my other USB drive (that still has fat32) that has OPL v1.0 - OPL v1.0 does not launch and is stuck at a black screen instead.

most likely not BDMAssault fault/responsibility

> Additionally, FreeMcBoot Configurator shows the mass storage as blank.
that's a problem....

**Comment by RoboMWM** [comment]
> but on my other USB drive (that still has fat32) that has OPL v1.0 - OPL v1.0 does not launch and is stuck at a black screen instead.

Just tested again, and now it works with both regular FreeMcBoot and BDMAssault-modified FreeMcBoot, so not sure what happened there.

**Comment by RoboMWM** [comment]
> not BDMAssault fault/responsibility. OPL uses it's own usb driver

Ah ok, good to know - I've been spending several hours these past couple days trying to figure out all this information that's spread out amongst various forum posts, github issues, repos, and wikis lol.

**Comment by RoboMWM** [comment]
> > Additionally, FreeMcBoot Configurator shows the mass storage as blank.

> that's a problem....

Just tested this with vanilla FreeMcBoot, and FreeMcBoot Configurator is able to see the fat32 flash drive. Only BDMAssault-modified FreeMcBoot causes FreeMcBoot Configurator to not see anything on the fat32 flash drive.

(If it helps, I can close this issue and open another for just this, since I now know that these issues are separate.)

**Comment by israpps** [comment]
well. this is most likely the new usb drivers not liking your USB. else, it should not fail on OPL too

**Comment by RoboMWM** [comment]
Yea, I figured that might be it. However, this seems to 'fix' the issue: https://github.com/ps2homebrew/Open-PS2-Loader/issues/1311#issuecomment-2327445583 and now the USB can be seen in FreeMcBoot Configurator!
